import type { Metadata } from "next";
import { Hind_Siliguri, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Suspense } from "react";
import Marquee from "@/components/Marquee";
import { ToastContainer } from "react-toastify";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiase", hindSiliguri.variable, "font-sans", geist.variable)}>
      <body className="min-h-full flex flex-col bg-base-200">
        <ToastContainer
          draggable={true}
          position="bottom-right"
        />
        <Navbar />
        <Suspense fallback={"Loading..."}>
          <Marquee />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
